#! /usr/bin/env python
"""
This scripts starts an sml process and wraps
a thin interpreter layer around it.
"""

import sys
import smlnj
import subprocess

if not smlnj.util.findprograms (["sml"]):
    print >> sys.stderr, 'unable to locate sml on your system.'
    print >> sys.stderr, 'be sure that it is properly installed and that your path variable is set correctly.'
    exit(1)

args  = ["sml"] + ([] if sys.argv[1:] is None else sys.argv[1:])
shell = smlnj.SMLShell (subprocess.Popen(args,
                                         stdout=subprocess.PIPE,
                                         stderr=subprocess.PIPE,
                                         stdin =subprocess.PIPE))

shell.main()
